title: "Shrut Prajapati | Data Scientist & ML Engineer"
description: "Professional Portfolio | Machine Learning | AI | Data Analytics"
theme: null  
baseurl: "" 
url: "https://your-github-username.github.io/Shrut-Portfolio"
include: ["_pages"]
