title: "Shrut Prajapati | Data Scientist & ML Engineer"
description: "Professional Portfolio | Machine Learning | AI | Data Analytics"
theme: null  # Ensure this is set correctly
baseurl: ""  # If the site is at root, keep this empty
url: "https://your-github-username.github.io/Shrut-Portfolio"
